### ISSUE TITLE
Is it possible to use this for the Landkreis Vechta?

### ISSUE THREAD

**Issue by HumongousFungus85** [Bouni/abfallplus#11]
The AWV (Abfallwirtschaft Vechta) uses Abfallplus somehow, however it uses it's own App. 
I can not use the original Abfallplus app and it prompts me to use the AWV app instead if I try.
Is it still possible to use this integration with it? Since I can not get the required IDs.
[AWV Website](https://www.abfallwirtschaft-vechta.de) 

Thanks in advance

**Comment by Bouni** [comment]
I had a quick look at theit website and it seems they do not embed the AbfallPlus web widget anywhere on their page.
I assume the've just licenced the App (IOS/Android). Without the widget the necessary keys cannot be extracted (I've not yet figured out how to reverse engeneer the Apps in order to get the keys).
Without the keys the HA integration does not work, sorry 🤷🏽
